# CUDA
#cuda_devices: '0'
npu_devices: '1'

# dataset
dataset:
  data_root: '/home/gt/tmp/MeshNet2/MeshNet/dataset/ModelNet40_processed'
  augment_data: false
  max_faces: 1024

# model
load_model: '/home/gt/tmp/MeshNet2/MeshNet/ckpt_root/MeshNet_best.pkl'

# MeshNet
MeshNet:
  structural_descriptor:
    num_kernel: 64
    sigma: 0.2
  mesh_convolution:
    aggregation_method: 'Concat'
  mask_ratio: 0.95
  dropout: 0.5
  num_classes: 40

# test config
batch_size: 128
retrieval_on: true
